### PR TITLE
Merge Initial DB Work

### PR DESCRIPTION
**Pull request by blackadar**
We'll need the first pass at the models to work on other components! This can change if needed with migrations in the future - be sure to check in your migrations into this branch so others' test data can be updated. We'll remove them all and keep a single migration at the end of the project.

### CODE REVIEW

**Comment by blackadar** [comment]
@everyone review pls

**Review by rlawton1243 — APPROVED** [review]
Looks good to me

**Comment by benclermontt** [comment]
How tf do I approve this

**Review by benclermontt — APPROVED** [review]
Nevermind figured it out

**Pull request merged**
